export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_SINGLE_MOVIE = "FETCH_SINGLE_MOVIE";
export const CREATE_MOVIE = "CREATE_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
